In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("sales_data.csv")
df.head()

    product  price  quantity
0       Pen   10.0       2.0
1      Book   50.0       1.0
2  Notebook    NaN       3.0
3    Pencil    5.0       5.0
4    Eraser    2.0      10.0

In [3]:
df.tail()

       product    price  quantity
12      Laptop  55000.0       1.0
13       Mouse    800.0       2.0
14    Keyboard   1200.0       1.0
15  Headphones   1500.0       2.0
16         Pen     10.0       2.0

In [4]:
df.shape

(17, 3)

In [5]:
df.columns

Index(['product', 'price', 'quantity'], dtype='str')

In [6]:
df.dtypes

product         str
price       float64
quantity    float64
dtype: object

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   product   17 non-null     str
 1   price     16 non-null     float64
 2   quantity  16 non-null     float64
dtypes: float64(2), str(1)
memory usage: 540.0 bytes

In [8]:
df.isnull().sum()

product     0
price       1
quantity    1
dtype: int64

In [9]:
df["price"] = df["price"].fillna(df["price"].median())
df["quantity"] = df["quantity"].fillna(df["quantity"].median())

In [10]:
df_dropped = df.dropna()

In [11]:
df.isnull().sum()

product     0
price       0
quantity    0
dtype: int64

In [12]:
df[["product", "price"]]

       product    price
0          Pen     10.0
1         Book     50.0
2     Notebook     37.5
3       Pencil      5.0
4       Eraser      2.0
5       Marker     25.0
6          Pen     10.0
7        Scale     15.0
8          Bag    500.0
9       Bottle    100.0
10        Book     50.0
11   Sharpener      3.0
12      Laptop  55000.0
13       Mouse    800.0
14    Keyboard   1200.0
15  Headphones   1500.0
16         Pen     10.0

In [13]:
df[df["price"] > 50]

       product    price  quantity
8          Bag    500.0       1.0
9       Bottle    100.0       2.0
12      Laptop  55000.0       1.0
13       Mouse    800.0       2.0
14    Keyboard   1200.0       1.0
15  Headphones   1500.0       2.0

In [14]:
df[df["quantity"] > 2]

      product  price  quantity
2    Notebook   37.5       3.0
3      Pencil    5.0       5.0
4      Eraser    2.0      10.0
11  Sharpener    3.0       4.0

In [15]:
df = df.drop_duplicates()

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df["total_amount"] = df["price"] * df["quantity"]
df.head()

    product  price  quantity  total_amount
0       Pen   10.0       2.0          20.0
1      Book   50.0       1.0          50.0
2  Notebook   37.5       3.0         112.5
3    Pencil    5.0       5.0          25.0
4    Eraser    2.0      10.0          20.0

In [18]:
df.to_csv("cleaned_sales_data.csv", index=False)

 Summary of Assignment

The dataset was loaded using Pandas. Data exploration was performed using head(), tail(), shape, columns, and info(). Missing values were checked and handled using median and default values. Duplicate rows were removed to ensure data consistency. A new column total_amount was created using price multiplied by quantity. Finally, the cleaned dataset was saved as a CSV file.